[2025-10-23T18:38:05.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-23T18:38:05.622+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airdna_etl_dag.extract1 manual__2025-10-23T18:37:56.997789+00:00 [queued]>
[2025-10-23T18:38:05.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airdna_etl_dag.extract1 manual__2025-10-23T18:37:56.997789+00:00 [queued]>
[2025-10-23T18:38:05.643+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-23T18:38:05.675+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract1> on 2025-10-23 18:37:56.997789+00:00
[2025-10-23T18:38:05.712+0000] {standard_task_runner.py:63} INFO - Started process 214 to run task
[2025-10-23T18:38:05.719+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airdna_etl_dag', 'extract1', 'manual__2025-10-23T18:37:56.997789+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_etl_dag.py', '--cfg-path', '/tmp/tmpsziym25n']
[2025-10-23T18:38:05.727+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask extract1
[2025-10-23T18:38:05.860+0000] {task_command.py:426} INFO - Running <TaskInstance: airdna_etl_dag.extract1 manual__2025-10-23T18:37:56.997789+00:00 [running]> on host ae3d9fdb668e
[2025-10-23T18:38:06.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airdna_etl_dag' AIRFLOW_CTX_TASK_ID='extract1' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:37:56.997789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:37:56.997789+00:00'
[2025-10-23T18:38:06.167+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-23T18:38:06.213+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-23T18:38:06.217+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airbnb_etl_dag.py", line 39, in extract1
    API_KEY = API_KEY
              ^^^^^^^
UnboundLocalError: cannot access local variable 'API_KEY' where it is not associated with a value
[2025-10-23T18:38:06.276+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=airdna_etl_dag, task_id=extract1, run_id=manual__2025-10-23T18:37:56.997789+00:00, execution_date=20251023T183756, start_date=20251023T183805, end_date=20251023T183806
[2025-10-23T18:38:06.316+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 111 for task extract1 (cannot access local variable 'API_KEY' where it is not associated with a value; 214)
[2025-10-23T18:38:06.342+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-23T18:38:06.376+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
