[2025-10-21T15:20:35.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T15:20:35.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_etl_pipeline.extract_airbnb_listings manual__2025-10-21T15:17:30.921906+00:00 [queued]>
[2025-10-21T15:20:35.452+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_etl_pipeline.extract_airbnb_listings manual__2025-10-21T15:17:30.921906+00:00 [queued]>
[2025-10-21T15:20:35.454+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-21T15:20:35.473+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_airbnb_listings> on 2025-10-21 15:17:30.921906+00:00
[2025-10-21T15:20:35.485+0000] {standard_task_runner.py:63} INFO - Started process 239 to run task
[2025-10-21T15:20:35.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbnb_etl_pipeline', 'extract_airbnb_listings', 'manual__2025-10-21T15:17:30.921906+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_etl_dag.py', '--cfg-path', '/tmp/tmpzjjvljez']
[2025-10-21T15:20:35.496+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask extract_airbnb_listings
[2025-10-21T15:20:35.578+0000] {task_command.py:426} INFO - Running <TaskInstance: airbnb_etl_pipeline.extract_airbnb_listings manual__2025-10-21T15:17:30.921906+00:00 [running]> on host 5bfcc774b24c
[2025-10-21T15:20:35.719+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbnb_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_airbnb_listings' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T15:17:30.921906+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T15:17:30.921906+00:00'
[2025-10-21T15:20:35.721+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T15:20:36.849+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T15:20:36.852+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airbnb_etl_dag.py", line 59, in extract_airbnb_listings
    df.to_csv("/opt/airflow/data/airbnb_listings_raw.csv", index=False)
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/data'
[2025-10-21T15:20:36.898+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=airbnb_etl_pipeline, task_id=extract_airbnb_listings, run_id=manual__2025-10-21T15:17:30.921906+00:00, execution_date=20251021T151730, start_date=20251021T152035, end_date=20251021T152036
[2025-10-21T15:20:36.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task extract_airbnb_listings (Cannot save file into a non-existent directory: '/opt/***/data'; 239)
[2025-10-21T15:20:36.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-21T15:20:37.018+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-21T15:20:37.026+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
